In [18]:
import cvxpy as cvx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import *

# Non-Negative Matrix Factorization
___

## Introduction
***

### Why are non-negative matrices important?

Data in many applications is defined on a positive-semidefinite range:

- Computer Vision (Pixels defined on $[0,255]$),
- Speech recognition (decibels on a scale of $[-96, 0]$ can be transformed),
- EEG signals (voltage $[µV]$ defined on $[5, 100]$),
- Power consumption ($\geq 0$),
- Frequency (for example in histograms $\geq 0$),
<br>
...


# Non-Negative Matrix Factorization
___

## Introduction
***

### How is a non-negative matrix $X$ obtained?

<img src="img/posMaApp.png" style="float: left;" width="600">

# Non-Negative Matrix Factorization
___

## Properties of Non-Negative Matrices
***

Let $X \in \mathbb{R}^{f \times n}$ be a matrix,
* the columns of which contain samples and
* the rows of which contain features.

Hence, the symbol 
* $f $  denotes the amount of features and
* $n $  the amount of observations/samples.

Matrix $X_{+}$ is non-negative if all its entries

$x_{i,j} \geq 0,$ $\forall i, j$.

# Non-Negative Matrix Factorization
___

## Matrix Factorization
***

### Problem Statement

Let $X \in \mathbb{R}^{f \times n}_{+}$ be a matrix. 

Find two matrices $F$ and $W$, so that

$X = FW$.

---

For $F$ and $W$ must hold, that 

$F \in \mathbb{R}^{f \times r}_{+}$ and $W \in \mathbb{R}^{f \times n}_{+}$.


# Non-Negative Matrix Factorization
___

## Chosen paper
***

### Factoring nonnegative matrices with linear programs
### Bittdorf, Recht et. al.

#### Abstract:

- Paper presents an approach to factor nonnegative matrices using linear programs
- Data-driven approach
- Most dominant features are used to represent others
- Given a data matrix $X$, a matrix $C$ is identified by the algorithm, so that $X \approx CX$

#### Following slides:

- Explenation of the method
- Presentation of a simple example
- Implementation and verification of solution

# Non-Negative Matrix Factorization
___

## Example and Theory
***
Consider a given non-negative data-matrix

\begin{align*}
~~~X=\begin{pmatrix}
1&1&0&1&0&1\\
1&0&2&3&0&1\\
2&2&0&2&0&2
\end{pmatrix}
\end{align*}

where rows $\hat{=} $ features ($f=\#$features), columns $\hat{=}$  data-points ($n=\#$data-points)

# Non-Negative Matrix Factorization
___

## Example and Theory
***
\begin{align*}
\textbf{First main idea:} \text{ Find matrix } C\in \mathbb{R}^{3\times 3} \text{ such that }X=CX 
\end{align*}

Since the third row is twice the first one, you can easily determine $C$ as
\begin{align*}
C=\begin{pmatrix}
0 & 0 & \frac{1}{2}\\
0&1&0 \\
0&0&1
\end{pmatrix}.
\end{align*}
The rows in $X$ corresponding to the diagonal entries of $C$ equal one are called hott topics.
Now one has a exact NMF of $X$:
\begin{equation*}
X=FW
\end{equation*}

# Non-Negative Matrix Factorization
___

## Example and Theory
***
The rows in $X$ corresponding to the diagonal entries of $C$ equal one are called $\textbf{hott topics}$.

Based on the matrix $C$ one construct $F\in\mathbb{R}^{f\times r}$ and $W\in\mathbb{R}^{r\times n}$ by extracting the non-zero columns of $C$ and the hott topics of $X$. In our example one gets
\begin{align*}
&X=\begin{pmatrix}
1&1&0&1&0&1\\
1&0&2&3&0&1\\
2&2&0&2&0&2
\end{pmatrix} \rightarrow C=\begin{pmatrix}
0 & 0 & \frac{1}{2}\\
0&1&0 \\
0&0&1
\end{pmatrix}\\ \rightarrow &F= \begin{pmatrix}
0 & \frac{1}{2} \\
1&0 \\
0&1 
\end{pmatrix}~ \text{ and }~W=\begin{pmatrix}
1&0&2&3&0&1\\
2&2&0&2&0&2
\end{pmatrix}. 
\end{align*}

# Non-Negative Matrix Factorization
___

## Example and Theory
***
<img src="img/convex_set.png" style="float: left;" width="400">

# Non-Negative Matrix Factorization
___

## Example and Theory
***
In general, determining $C$ is not that easy as in this example. It can be formulated as a linear program:
\begin{equation*}
\textbf{LP to solve:} ~~~\min_{C\in \Phi(X)} p^T \text{diag}(C)
\end{equation*}
where $X$ is a non-negative data-matrix, $p$ is a given price-vector with distinct values and the constraint set is defined as
\begin{equation*}
\Phi\left(X\right):=\lbrace C\geq \textbf{0} \mid CY=Y,~\text{tr}\left(C\right)=r,~C_{jj}\leq 1~\forall j,~C_{ij}\leq C_{jj}~\forall i,j \rbrace
\end{equation*}

# Non-Negative Matrix Factorization
___

## Example and Theory
***
It is easy to show that this set is convex. By definition of convexity and with $C_1,C_2\in \Phi(X)$ and $\theta\in \left[0,1\right]$ it holds 
\begin{align*}
C_3&:=\underbrace{\theta}_{\geq 0} \underbrace{C_1}_{\geq\textbf{0}}+(\underbrace{1-\theta}_{\geq 0}) \underbrace{C_2}_{\geq\textbf{0}}\geq \textbf{0},\\
C_3Y&=\theta \underbrace{C_1Y}_{=Y}+(1-\theta)\underbrace{C_2Y}_{=Y}=Y,\\
C_{jj}^{(3)}&=\theta \underbrace{C_{jj}^{(1)}}_{\leq 1}+(1-\theta)\underbrace{C_{jj}^{(2)}}_{\leq 1} \leq \theta +(1-\theta)=1~~\forall j,\\
C_{ij}^{(3)}&=\theta \underbrace{C_{ij}^{(1)}}_{\leq C_{jj}^{(1)}}+(1-\theta) \underbrace{C_{ij}^{(2)}}_{\leq C_{jj}^{(2)}}\leq \theta C_{jj}^{(1)}+(1-\theta)C_{jj}^{(2)}=C_{jj}^{(3)} ~~\forall i,j.
\end{align*}

# Non-Negative Matrix Factorization
___

## Example and Theory
***
<img src="img/algorithm_2.png" style="float: left;" width="1000">

# Non-Negative Matrix Factorization
___

## Example and Theory
***
$\textbf{So far:}$ $X$ has an exact separable $r$-rank factorization.

$\textbf{Now:}$ $X$ has an approximately separable $r$-rank factorization, i.e.
\begin{align*}
X=Y+\Delta 
\end{align*}
where 

- $Y$ has an exact separable $r$-rank factorization,
- $\Delta$ is an Error-matrix with $\Vert \Delta \Vert_{\infty,1}\leq \epsilon$

# Non-Negative Matrix Factorization
___

## Example and Theory
***
Adjust the constraint set 
\begin{equation*}
\Phi_{2\epsilon}:=\lbrace C\geq \textbf{0} \mid \Vert CX-X \Vert_{\infty,1}\leq 2\epsilon,~\text{tr}\left( C \right)=r,~ C_{jj}\leq 1~\forall j,~ C_{ij}\leq C_{jj}~\forall i,j  \rbrace.
\end{equation*}

# Non-Negative Matrix Factorization
___

## Example and Theory
***
<img src="img/algorithm_3.png" style="float: left;" width="1000">

# Non-Negative Matrix Factorization
___

## Implementation: Algorithm 2
***
<img src="img/algorithm_2.png" style="float: left;" width="1000">

In [19]:
print("Algorithm 2: Separable Nonnegative Matrix Factorization by Linear Programming\n")

## Functions
###-----------------------------------------------

def distinct_integral_vector( num_values , mode):
    output_vector = np.zeros((num_values,1))
    for i in range(0,num_values):
        if mode == "ascending":
            output_vector[i] = i
        else:
            output_vector[i] = num_values - i - 1
    return output_vector

###-----------------------------------------------

def normalize_rows( input_matrix ):
    output_matrix = np.zeros((input_matrix.shape[0], input_matrix.shape[1]))
    for i in range(0, input_matrix.shape[0]): #For all rows
        sum_current_row = 0.0
        for j in range(0, input_matrix.shape[1]): #For all columns
            sum_current_row += input_matrix[i, j]
        for j in range(0, input_matrix.shape[1]): #For all columns
            output_matrix[i,j] = input_matrix[i,j]/sum_current_row
    return np.matrix(output_matrix)

###-----------------------------------------------

def build_W_separable( matrix_C, matrix_Y_norm ):
    output_matrix_rows = 0
    output_matrix_columns = matrix_Y_norm.shape[1]
    simplicial_rows = []
    
    for i in range(0, C.shape[0]):
        if C[i,i] == 1.0:
            output_matrix_rows += 1
            simplicial_rows.append(i)
    
    output_matrix = np.zeros((output_matrix_rows, output_matrix_columns))
    
    for i in range(0, len(simplicial_rows)): #New columns
        for j in range(0, output_matrix_columns):
            output_matrix[i,j] = matrix_Y_norm[simplicial_rows[i], j]
            
    return output_matrix

###-----------------------------------------------

def build_F_separable( matrix_C ):
    output_matrix_columns = 0
    output_matrix_rows = matrix_C.shape[0]
    separable_columns = []
    
    for i in range(0, C.shape[0]):
        if C[i,i] == 1.0:
            output_matrix_columns += 1
            separable_columns.append(i)
    
    output_matrix = np.zeros((output_matrix_rows, output_matrix_columns))
    
    for j in range(0, output_matrix_columns): #New columns
        for i in range(0, output_matrix_rows): #Row entries
            output_matrix[i,j] = matrix_C[i, separable_columns[j]]
            
    return output_matrix
        
###-----------------------------------------------

# INPUT DATA
#-----------

r = 2

Y = np.matrix([[1,1,0,1,0,1],[1,0,2,3,0,1],[2,2,0,2,0,2]])
Y_norm = normalize_rows(Y)
Yn = Y_norm

f = Y.shape[0]
n = Y.shape[1]

C = cvx.Variable((f,f), nonneg = True)
p = distinct_integral_vector(f, "ascending")

print("Input data:\n")
print("Data matrix Y:")
print(Y,"\n")
print("Normalized input data:\n")
print("Data matrix Y_norm:")
print(Y_norm,"\n")
print("Vector p:")
print(p, "\n")
print("Find matrix C by optimization:")
print("--------------\n")

## Model
###-----------------------------------------------

objective = cvx.Minimize( p.T * cvx.diag(C))

constraints = [C * Y_norm == Y_norm,
               cvx.trace(C) == r]

for j in range(0,f): # columns
    for i in range(0,f): #rows
        #constraints += [C[i,j] >= 0]
        if j == i:
            constraints += [C[i,j] <= 1]
        else:
            constraints += [C[i, j] <= C[j,j]]

prob = cvx.Problem(objective, constraints)#
print("Model built.\n")

prob.solve(solver = cvx.GLPK)
print("Model solved.\n")
print("--------------\n")

print("Results:\n")
print("Variable C:")
C = C.value
print(C,"\n")
print("||Y_norm - C * Y_norm||_inf,1:")
print(np.linalg.norm(C * Y_norm - Y_norm, np.inf), "\n")
print("--------------\n")
print("Factorization:\n")
print("Matrix W:")

## Factorization
###-----------------------------------------------

W = build_W_separable(C, Y_norm)
print(W, "\n")
print("Matrix F:")
F = build_F_separable(C)
print(F, "\n")
print("Y_norm = F * W")
print(np.matrix(F) * np.matrix(W),"\n")



Algorithm 2: Separable Nonnegative Matrix Factorization by Linear Programming

Input data:

Data matrix Y:
[[1 1 0 1 0 1]
 [1 0 2 3 0 1]
 [2 2 0 2 0 2]] 

Normalized input data:

Data matrix Y_norm:
[[0.25       0.25       0.         0.25       0.         0.25      ]
 [0.14285714 0.         0.28571429 0.42857143 0.         0.14285714]
 [0.25       0.25       0.         0.25       0.         0.25      ]] 

Vector p:
[[0.]
 [1.]
 [2.]] 

Find matrix C by optimization:
--------------

Model built.

Model solved.

--------------

Results:

Variable C:
[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]] 

||Y_norm - C * Y_norm||_inf,1:
0.0 

--------------

Factorization:

Matrix W:
[[0.25       0.25       0.         0.25       0.         0.25      ]
 [0.14285714 0.         0.28571429 0.42857143 0.         0.14285714]] 

Matrix F:
[[1. 0.]
 [0. 1.]
 [1. 0.]] 

Y_norm = F * W
[[0.25       0.25       0.         0.25       0.         0.25      ]
 [0.14285714 0.         0.28571429 0.42857143 0.         0.1428

# Non-Negative Matrix Factorization
___

## Implementation: Algorithm 3
***
<img src="img/algorithm_3.png" style="float: left;" width="1000">

In [20]:
print("Algorithm 3: Approximably Separable Nonnegative Matrix Factorization by Linear Programming\n")

## Functions
###-----------------------------------------------

def distinct_integral_vector( num_values , mode):
    output_vector = np.zeros((num_values,1))
    for i in range(0,num_values):
        if mode == "ascending":
            output_vector[i] = i
        else:
            output_vector[i] = num_values - i - 1
    return output_vector

###-----------------------------------------------

def normalize_rows( input_matrix ):
    output_matrix = np.zeros((input_matrix.shape[0], input_matrix.shape[1]))
    for i in range(0, input_matrix.shape[0]): #For all rows
        sum_current_row = 0.0
        for j in range(0, input_matrix.shape[1]): #For all columns
            sum_current_row += input_matrix[i, j]
        for j in range(0, input_matrix.shape[1]): #For all columns
            output_matrix[i,j] = input_matrix[i,j]/sum_current_row
    return np.matrix(output_matrix)

###-----------------------------------------------

def build_W_nonseparable( matrix_C, matrix_X_norm ):
    output_matrix_rows = 0
    output_matrix_columns = matrix_X_norm.shape[1]
    simplicial_rows = []
    
    for i in range(0, C.shape[0]):
        if abs(matrix_C[i,i] - 1.0) <= 0.001:
            output_matrix_rows += 1
            simplicial_rows.append(i)
    
    output_matrix = np.zeros((output_matrix_rows, output_matrix_columns))
    
    for i in range(0, len(simplicial_rows)): #New columns
        for j in range(0, output_matrix_columns):
            output_matrix[i,j] = matrix_X_norm[simplicial_rows[i], j]
            
    return output_matrix

###-----------------------------------------------

def build_F_nonseparable( matrix_C ):
    output_matrix_columns = 0
    output_matrix_rows = matrix_C.shape[0]
    separable_columns = []
    
    for i in range(0, C.shape[0]):
        if abs(matrix_C[i,i] - 1.0) <= 0.001:
            output_matrix_columns += 1
            separable_columns.append(i)
    
    output_matrix = np.zeros((output_matrix_rows, output_matrix_columns))
    
    for j in range(0, output_matrix_columns): #New columns
        for i in range(0, output_matrix_rows): #Row entries
            output_matrix[i,j] = matrix_C[i, separable_columns[j]]
            
    return output_matrix

###-----------------------------------------------

## Input Data
###-----------------------------------------------

r = 2

X = np.matrix([[1,1,0,1,1,1],[1,0,2,3,0,1],[2,2,0,2,0,2]])
X_norm = normalize_rows(Y)

f = X.shape[0]
n = X.shape[1]

C = cvx.Variable((f,f), nonneg = True)
p = distinct_integral_vector(f, "ascending")

print("Input data:\n")
print("Data matrix X:")
print(Y,"\n")
print("Normalized input data:\n")
print("Data matrix X_norm:")
print(Y_norm,"\n")
print("Vector p:")
print(p, "\n")
print("--------------\n")

## Model #1
###-----------------------------------------------

objective_find_C = cvx.Minimize( p.T * cvx.diag(C) )

constraints_find_C = [cvx.norm( C * X_norm - X_norm ) <= 0.3,
               cvx.trace(C) == r]

for j in range(0,f): # columns
    for i in range(0,f): #rows
        #constraints += [C[i,j] >= 0]
        if j == i:
            constraints_find_C += [C[i,j] <= 1]
        else:
            constraints_find_C += [C[i, j] <= C[j,j]]

prob_find_C = cvx.Problem(objective_find_C, constraints_find_C)#
print("Model built.\n")

prob_find_C.solve()
print("Model solved.\n")
print("--------------\n")

print("Results:\n")
print("Variable C:")
C = C.value
print(C,"\n")
print("||X_norm - C * X_norm||_inf,1:")
print(np.linalg.norm(C * X_norm - X_norm, np.inf), "\n")

## Factorization #1
###-----------------------------------------------

print("Factorization:\n")
print("Matrix W:")
W = build_W_nonseparable(C, X_norm)
print(W, "\n")

## Model #2
###-----------------------------------------------

print("Find F by solving an optimization problem:")
print("--------------\n")

F_dep = build_F_nonseparable(C)
F = cvx.Variable((Y_norm.shape[0], W.shape[0]))

objective_find_F = cvx.Minimize(cvx.norm(X_norm - F * W, "inf"))

prob_find_F = cvx.Problem(objective_find_F)
print("Model built.\n")

prob_find_F.solve()
print("Model solved.\n")
print("--------------\n")
print("Matrix F:")
print(F.value, "\n")
print("X_norm = F * W")
print(np.matrix(F.value) * W,"\n")

print("||X_norm - F * W||_inf,1:")
print(np.linalg.norm(X_norm - np.matrix(F.value) * W, np.inf), "\n")

print("||X_norm - F_dep * W||_inf,1:")
print(np.linalg.norm(X_norm - np.matrix(F_dep) * W, np.inf), "\n")

Algorithm 3: Approximably Separable Nonnegative Matrix Factorization by Linear Programming

Input data:

Data matrix X:
[[1 1 0 1 0 1]
 [1 0 2 3 0 1]
 [2 2 0 2 0 2]] 

Normalized input data:

Data matrix X_norm:
[[0.25       0.25       0.         0.25       0.         0.25      ]
 [0.14285714 0.         0.28571429 0.42857143 0.         0.14285714]
 [0.25       0.25       0.         0.25       0.         0.25      ]] 

Vector p:
[[0.]
 [1.]
 [2.]] 

--------------

Model built.

Model solved.

--------------

Results:

Variable C:
[[1.         0.19442079 0.        ]
 [0.29747247 1.         0.        ]
 [0.7161661  0.32748827 0.        ]] 

||X_norm - C * X_norm||_inf,1:
0.2974724648000622 

Factorization:

Matrix W:
[[0.25       0.25       0.         0.25       0.         0.25      ]
 [0.14285714 0.         0.28571429 0.42857143 0.         0.14285714]] 

Find F by solving an optimization problem:
--------------

Model built.

Model solved.

--------------

Matrix F:
[[ 1.00000000e+00 -5

# Non-Negative Matrix Factorization
___

## Conclusion
***

#### Advantages and Disadvantages:

- No assumptions that features follow a certain function (unlike linear regression)
- Assumed that features lie in one convex hull
- Assumptions regarding parameters $r$ and $\epsilon$

#### Application:

- Dimensionality reduction
- Efficient for large data sets


# Non-Negative Matrix Factorization
___

## Thanks for your attention. Questions?
***

# Non-Negative Matrix Factorization
___

## Backup Slides
***
<img src="img/algorithm_4.png" style="float: left;" width="800">

# Non-Negative Matrix Factorization
___

## Backup Slides
***
<img src="img/error.png" style="float: left;" width="800">